# American Community Survey  2017-2013 [5-year]

[ACS 2017-2013](https://www.census.gov/data/developers/data-sets/acs-5year/2017.html) 

[Census Data API User Guide](https://www.census.gov/content/dam/Census/data/developers/api-user-guide/api-guide.pdf)

In [6]:
import pandas as pd

In [7]:
from urllib.request import urlopen
from json import loads

In [8]:
# url = "https://api.census.gov/data/2017/acs/acs5?get=NAME,B01001_004E&for=block%20group:*&in=state:06%20county:*"

# for all counties in California
# B01001_004E = Total Male Estimates 5-9 years in California counties

In [9]:
directory = "https://api.census.gov/data/2017/acs/acs5.html"

## Dataframe for Total Male Estimates 5 - 9 years

B01001_004E = Estimate!!Total!!Male!!5 to 9 years

In [28]:
url4 = "https://api.census.gov/data/2017/acs/acs5?get=NAME,B01001_004E&for=block%20group:*&in=state:06%20county:073"

# San Diego County = 073
# in url B01001_004E = Estimate!!Total!!Male!!5 to 9 years

response = urlopen(url4)
data = loads(response.read())

data

[['NAME', 'B01001_004E', 'state', 'county', 'tract', 'block group'],
 ['Block Group 2, Census Tract 178.08, San Diego County, California',
  '82',
  '06',
  '073',
  '017808',
  '2'],
 ['Block Group 4, Census Tract 178.08, San Diego County, California',
  '33',
  '06',
  '073',
  '017808',
  '4'],
 ['Block Group 3, Census Tract 178.08, San Diego County, California',
  '49',
  '06',
  '073',
  '017808',
  '3'],
 ['Block Group 1, Census Tract 178.08, San Diego County, California',
  '0',
  '06',
  '073',
  '017808',
  '1'],
 ['Block Group 1, Census Tract 191.01, San Diego County, California',
  '95',
  '06',
  '073',
  '019101',
  '1'],
 ['Block Group 2, Census Tract 191.01, San Diego County, California',
  '55',
  '06',
  '073',
  '019101',
  '2'],
 ['Block Group 3, Census Tract 191.01, San Diego County, California',
  '200',
  '06',
  '073',
  '019101',
  '3'],
 ['Block Group 3, Census Tract 170.15, San Diego County, California',
  '165',
  '06',
  '073',
  '017015',
  '3'],
 ['Block Group 2, Census Tract 83.10, San Diego County, California',
  '0',
  '06',
  '073',
  '008310',
  '2'],
 ['Block Group 3, Census Tract 83.10, San Diego County, California',
  '86',
  '06',
  '073',
  '008310',
  '3'],
 ['Block Group 1, Census Tract 83.29, San Diego County, California',
  '64',
  '06',
  '073',
  '008329',
  '1'],
 ['Block Group 1, Census Tract 83.40, San Diego County, California',
  '135',
  '06',
  '073',
  '008340',
  '1'],
 ['Block Group 2, Census Tract 83.40, San Diego County, California',
  '0',
  '06',
  '073',
  '008340',
  '2'],
 ['Block Group 1, Census Tract 83.41, San Diego County, California',
  '17',
  '06',
  '073',
  '008341',
  '1'],
 ['Block Group 1, Census Tract 83.50, San Diego County, California',
  '96',
  '06',
  '073',
  '008350',
  '1'],
 ['Block Group 2, Census Tract 83.50, San Diego County, California',
  '15',
  '06',
  '073',
  '008350',
  '2'],
 ['Block Group 3, Census Tract 83.50, San Diego County, California',
  '33',
  '06',
  '073',
  '008350',
  '3'],
 ['Block Group 1, Census Tract 83.58, San Diego County, California',
  '20',
  '06',
  '073',
  '008358',
  '1'],
 ['Block Group 2, Census Tract 83.58, San Diego County, California',
  '0',
  '06',
  '073',
  '008358',
  '2'],
 ['Block Group 3, Census Tract 83.58, San Diego County, California',
  '18',
  '06',
  '073',
  '008358',
  '3'],
 ['Block Group 4, Census Tract 83.58, San Diego County, California',
  '96',
  '06',
  '073',
  '008358',
  '4'],
 ['Block Group 3, Census Tract 86, San Diego County, California',
  '0',
  '06',
  '073',
  '008600',
  '3'],
 ['Block Group 2, Census Tract 86, San Diego County, California',
  '51',
  '06',
  '073',
  '008600',
  '2'],
 ['Block Group 1, Census Tract 86, San Diego County, California',
  '125',
  '06',
  '073',
  '008600',
  '1'],
 ['Block Group 2, Census Tract 90, San Diego County, California',
  '0',
  '06',
  '073',
  '009000',
  '2'],
 ['Block Group 1, Census Tract 90, San Diego County, California',
  '89',
  '06',
  '073',
  '009000',
  '1'],
 ['Block Group 2, Census Tract 91.02, San Diego County, California',
  '23',
  '06',
  '073',
  '009102',
  '2'],
 ['Block Group 1, Census Tract 91.02, San Diego County, California',
  '0',
  '06',
  '073',
  '009102',
  '1'],
 ['Block Group 4, Census Tract 93.01, San Diego County, California',
  '55',
  '06',
  '073',
  '009301',
  '4'],
 ['Block Group 1, Census Tract 93.01, San Diego County, California',
  '9',
  '06',
  '073',
  '009301',
  '1'],
 ['Block Group 2, Census Tract 93.01, San Diego County, California',
  '50',
  '06',
  '073',
  '009301',
  '2'],
 ['Block Group 1, Census Tract 139.03, San Diego County, California',
  '50',
  '06',
  '073',
  '013903',
  '1'],
 ['Block Group 2, Census Tract 139.03, San Diego County, California',
  '46',
  '06',
  '073',
  '013903',
  '2'],
 ['Block Group 1, Census Tract 139.07, San Diego County, California',
  '96',
  '06',
  '073',
  '013907',
  '1'],
 ['Block Group 2, Census Tract 139.07, San Diego County, California',
  '142',
  '06',
  '073',
  '013907',
  '2'],
 ['Block Group 3, Census Tract 146.02, San Diego County, California',
  '106',
  '06',
  '073',
  '014602',
  '3'],
 ['Block Group 2, Census Tract 146.02, San Diego County, California',
  '85',
  '06',
  '073',
  '014602',
  '2'],
 ['Block Group 1, Census Tract 146.02, San Diego County, California',
  '29',
  '06',
  '073',
  '014602',
  '1'],
 ['Block Group 2, Census Tract 148.03, San Diego County, California',
  '92',
  '06',
  '073',
  '014803',
  '2'],
 ['Block Group 3, Census Tract 148.03, San Diego County, California',
  '0',
  '06',
  '073',
  '014803',
  '3'],
 ['Block Group 3, Census Tract 92.01, San Diego County, California',
  '11',
  '06',
  '073',
  '009201',
  '3'],
 ['Block Group 2, Census Tract 92.01, San Diego County, California',
  '139',
  '06',
  '073',
  '009201',
  '2'],
 ['Block Group 4, Census Tract 92.01, San Diego County, California',
  '74',
  '06',
  '073',
  '009201',
  '4'],
 ['Block Group 1, Census Tract 92.01, San Diego County, California',
  '23',
  '06',
  '073',
  '009201',
  '1'],
 ['Block Group 5, Census Tract 97.06, San Diego County, California',
  '17',
  '06',
  '073',
  '009706',
  '5'],
 ['Block Group 6, Census Tract 97.06, San Diego County, California',
  '38',
  '06',
  '073',
  '009706',
  '6'],
 ['Block Group 1, Census Tract 97.06, San Diego County, California',
  '128',
  '06',
  '073',
  '009706',
  '1'],
 ['Block Group 3, Census Tract 97.06, San Diego County, California',
  '25',
  '06',
  '073',
  '009706',
  '3'],
 ['Block Group 4, Census Tract 97.06, San Diego County, California',
  '56',
  '06',
  '073',
  '009706',
  '4'],
 ['Block Group 7, Census Tract 97.06, San Diego County, California',
  '0',
  '06',
  '073',
  '009706',
  '7'],
 ['Block Group 2, Census Tract 97.06, San Diego County, California',
  '59',
  '06',
  '073',
  '009706',
  '2'],
 ['Block Group 2, Census Tract 100.10, San Diego County, California',
  '31',
  '06',
  '073',
  '010010',
  '2'],
 ['Block Group 3, Census Tract 100.10, San Diego County, California',
  '58',
  '06',
  '073',
  '010010',
  '3'],
 ['Block Group 1, Census Tract 100.10, San Diego County, California',
  '0',
  '06',
  '073',
  '010010',
  '1'],
 ['Block Group 2, Census Tract 101.04, San Diego County, California',
  '108',
  '06',
  '073',
  '010104',
  '2'],
 ['Block Group 1, Census Tract 101.04, San Diego County, California',
  '11',
  '06',
  '073',
  '010104',
  '1'],
 ['Block Group 1, Census Tract 101.06, San Diego County, California',
  '66',
  '06',
  '073',
  '010106',
  '1'],
 ['Block Group 3, Census Tract 101.06, San Diego County, California',
  '69',
  '06',
  '073',
  '010106',
  '3'],
 ['Block Group 2, Census Tract 101.06, San Diego County, California',
  '125',
  '06',
  '073',
  '010106',
  '2'],
 ['Block Group 4, Census Tract 103, San Diego County, California',
  '10',
  '06',
  '073',
  '010300',
  '4'],
 ['Block Group 2, Census Tract 103, San Diego County, California',
  '100',
  '06',
  '073',
  '010300',
  '2'],
 ['Block Group 1, Census Tract 103, San Diego County, California',
  '0',
  '06',
  '073',
  '010300',
  '1'],
 ['Block Group 3, Census Tract 168.07, San Diego County, California',
  '35',
  '06',
  '073',
  '016807',
  '3'],
 ['Block Group 4, Census Tract 168.07, San Diego County, California',
  '33',
  '06',
  '073',
  '016807',
  '4'],
 ['Block Group 1, Census Tract 168.07, San Diego County, California',
  '26',
  '06',
  '073',
  '016807',
  '1'],
 ['Block Group 1, Census Tract 170.20, San Diego County, California',
  '37',
  '06',
  '073',
  '017020',
  '1'],
 ['Block Group 2, Census Tract 170.20, San Diego County, California',
  '46',
  '06',
  '073',
  '017020',
  '2'],
 ['Block Group 1, Census Tract 175.01, San Diego County, California',
  '7',
  '06',
  '073',
  '017501',
  '1'],
 ['Block Group 2, Census Tract 175.01, San Diego County, California',
  '24',
  '06',
  '073',
  '017501',
  '2'],
 ['Block Group 3, Census Tract 175.01, San Diego County, California',
  '41',
  '06',
  '073',
  '017501',
  '3'],
 ['Block Group 2, Census Tract 97.03, San Diego County, California',
  '19',
  '06',
  '073',
  '009703',
  '2'],
 ['Block Group 3, Census Tract 97.03, San Diego County, California',
  '31',
  '06',
  '073',
  '009703',
  '3'],
 ['Block Group 1, Census Tract 97.03, San Diego County, California',
  '53',
  '06',
  '073',
  '009703',
  '1'],
 ['Block Group 1, Census Tract 83.11, San Diego County, California',
  '9',
  '06',
  '073',
  '008311',
  '1'],
 ['Block Group 2, Census Tract 136.06, San Diego County, California',
  '5',
  '06',
  '073',
  '013606',
  '2'],
 ['Block Group 3, Census Tract 136.06, San Diego County, California',
  '17',
  '06',
  '073',
  '013606',
  '3'],
 ['Block Group 1, Census Tract 136.06, San Diego County, California',
  '30',
  '06',
  '073',
  '013606',
  '1'],
 ['Block Group 1, Census Tract 138.02, San Diego County, California',
  '50',
  '06',
  '073',
  '013802',
  '1'],
 ['Block Group 2, Census Tract 139.05, San Diego County, California',
  '22',
  '06',
  '073',
  '013905',
  '2'],
 ['Block Group 3, Census Tract 139.05, San Diego County, California',
  '9',
  '06',
  '073',
  '013905',
  '3'],
 ['Block Group 1, Census Tract 139.05, San Diego County, California',
  '59',
  '06',
  '073',
  '013905',
  '1'],
 ['Block Group 3, Census Tract 142, San Diego County, California',
  '14',
  '06',
  '073',
  '014200',
  '3'],
 ['Block Group 1, Census Tract 142, San Diego County, California',
  '88',
  '06',
  '073',
  '014200',
  '1'],
 ['Block Group 2, Census Tract 142, San Diego County, California',
  '65',
  '06',
  '073',
  '014200',
  '2'],
 ['Block Group 4, Census Tract 142, San Diego County, California',
  '35',
  '06',
  '073',
  '014200',
  '4'],
 ['Block Group 1, Census Tract 143, San Diego County, California',
  '54',
  '06',
  '073',
  '014300',
  '1'],
 ['Block Group 2, Census Tract 143, San Diego County, California',
  '102',
  '06',
  '073',
  '014300',
  '2'],
 ['Block Group 4, Census Tract 152, San Diego County, California',
  '17',
  '06',
  '073',
  '015200',
  '4'],
 ['Block Group 1, Census Tract 152, San Diego County, California',
  '0',
  '06',
  '073',
  '015200',
  '1'],
 ['Block Group 3, Census Tract 152, San Diego County, California',
  '16',
  '06',
  '073',
  '015200',
  '3'],
 ['Block Group 2, Census Tract 152, San Diego County, California',
  '34',
  '06',
  '073',
  '015200',
  '2'],
 ['Block Group 2, Census Tract 153.01, San Diego County, California',
  '57',
  '06',
  '073',
  '015301',
  '2'],
 ['Block Group 1, Census Tract 33.03, San Diego County, California',
  '162',
  '06',
  '073',
  '003303',
  '1'],
 ['Block Group 2, Census Tract 33.03, San Diego County, California',
  '96',
  '06',
  '073',
  '003303',
  '2'],
 ['Block Group 3, Census Tract 39.02, San Diego County, California',
  '41',
  '06',
  '073',
  '003902',
  '3'],
 ['Block Group 2, Census Tract 39.02, San Diego County, California',
  '35',
  '06',
  '073',
  '003902',
  '2'],
 ['Block Group 3, Census Tract 174.01, San Diego County, California',
  '15',
  '06',
  '073',
  '017401',
  '3'],
 ['Block Group 3, Census Tract 132.06, San Diego County, California',
  '55',
  '06',
  '073',
  '013206',
  '3'],
 ['Block Group 2, Census Tract 132.06, San Diego County, California',
  '20',
  '06',
  '073',
  '013206',
  '2'],
 ['Block Group 1, Census Tract 132.06, San Diego County, California',
  '116',
  '06',
  '073',
  '013206',
  '1'],
 ['Block Group 1, Census Tract 134.19, San Diego County, California',
  '334',
  '06',
  '073',
  '013419',
  '1'],
 ['Block Group 2, Census Tract 134.19, San Diego County, California',
  '32',
  '06',
  '073',
  '013419',
  '2'],
 ['Block Group 1, Census Tract 154.06, San Diego County, California',
  '72',
  '06',
  '073',
  '015406',
  '1'],
 ['Block Group 1, Census Tract 174.03, San Diego County, California',
  '0',
  '06',
  '073',
  '017403',
  '1'],
 ['Block Group 4, Census Tract 174.03, San Diego County, California',
  '41',
  '06',
  '073',
  '017403',
  '4'],
 ['Block Group 2, Census Tract 174.03, San Diego County, California',
  '25',
  '06',
  '073',
  '017403',
  '2'],
 ['Block Group 3, Census Tract 174.03, San Diego County, California',
  '55',
  '06',
  '073',
  '017403',
  '3'],
 ['Block Group 1, Census Tract 52, San Diego County, California',
  '24',
  '06',
  '073',
  '005200',
  '1'],
 ['Block Group 2, Census Tract 52, San Diego County, California',
  '47',
  '06',
  '073',
  '005200',
  '2'],
 ['Block Group 3, Census Tract 60, San Diego County, California',
  '16',
  '06',
  '073',
  '006000',
  '3'],
 ['Block Group 3, Census Tract 103, San Diego County, California',
  '39',
  '06',
  '073',
  '010300',
  '3'],
 ['Block Group 2, Census Tract 35.01, San Diego County, California',
  '0',
  '06',
  '073',
  '003501',
  '2'],
 ['Block Group 2, Census Tract 196.01, San Diego County, California',
  '0',
  '06',
  '073',
  '019601',
  '2'],
 ['Block Group 4, Census Tract 196.01, San Diego County, California',
  '34',
  '06',
  '073',
  '019601',
  '4'],
 ['Block Group 1, Census Tract 82, San Diego County, California',
  '0',
  '06',
  '073',
  '008200',
  '1'],
 ['Block Group 2, Census Tract 82, San Diego County, California',
  '0',
  '06',
  '073',
  '008200',
  '2'],
 ['Block Group 3, Census Tract 82, San Diego County, California',
  '25',
  '06',
  '073',
  '008200',
  '3'],
 ['Block Group 3, Census Tract 83.01, San Diego County, California',
  '49',
  '06',
  '073',
  '008301',
  '3'],
 ['Block Group 1, Census Tract 83.01, San Diego County, California',
  '0',
  '06',
  '073',
  '008301',
  '1'],
 ['Block Group 2, Census Tract 83.01, San Diego County, California',
  '0',
  '06',
  '073',
  '008301',
  '2'],
 ['Block Group 4, Census Tract 39.02, San Diego County, California',
  '31',
  '06',
  '073',
  '003902',
  '4'],
 ['Block Group 1, Census Tract 39.02, San Diego County, California',
  '23',
  '06',
  '073',
  '003902',
  '1'],
 ['Block Group 2, Census Tract 53, San Diego County, California',
  '0',
  '06',
  '073',
  '005300',
  '2'],
 ['Block Group 4, Census Tract 53, San Diego County, California',
  '0',
  '06',
  '073',
  '005300',
  '4'],
 ['Block Group 1, Census Tract 53, San Diego County, California',
  '0',
  '06',
  '073',
  '005300',
  '1'],
 ['Block Group 3, Census Tract 53, San Diego County, California',
  '0',
  '06',
  '073',
  '005300',
  '3'],
 ['Block Group 1, Census Tract 54, San Diego County, California',
  '0',
  '06',
  '073',
  '005400',
  '1'],
 ['Block Group 2, Census Tract 54, San Diego County, California',
  '0',
  '06',
  '073',
  '005400',
  '2'],
 ['Block Group 3, Census Tract 54, San Diego County, California',
  '0',
  '06',
  '073',
  '005400',
  '3'],
 ['Block Group 1, Census Tract 57, San Diego County, California',
  '0',
  '06',
  '073',
  '005700',
  '1'],
 ['Block Group 1, Census Tract 83.05, San Diego County, California',
  '0',
  '06',
  '073',
  '008305',
  '1'],
 ['Block Group 2, Census Tract 83.07, San Diego County, California',
  '29',
  '06',
  '073',
  '008307',
  '2'],
 ['Block Group 3, Census Tract 83.07, San Diego County, California',
  '4',
  '06',
  '073',
  '008307',
  '3'],
 ['Block Group 1, Census Tract 83.07, San Diego County, California',
  '24',
  '06',
  '073',
  '008307',
  '1'],
 ['Block Group 1, Census Tract 83.24, San Diego County, California',
  '181',
  '06',
  '073',
  '008324',
  '1'],
 ['Block Group 3, Census Tract 83.24, San Diego County, California',
  '19',
  '06',
  '073',
  '008324',
  '3'],
 ['Block Group 2, Census Tract 83.24, San Diego County, California',
  '175',
  '06',
  '073',
  '008324',
  '2'],
 ['Block Group 4, Census Tract 83.24, San Diego County, California',
  '44',
  '06',
  '073',
  '008324',
  '4'],
 ['Block Group 1, Census Tract 83.39, San Diego County, California',
  '13',
  '06',
  '073',
  '008339',
  '1'],
 ['Block Group 3, Census Tract 83.47, San Diego County, California',
  '91',
  '06',
  '073',
  '008347',
  '3'],
 ['Block Group 1, Census Tract 83.47, San Diego County, California',
  '121',
  '06',
  '073',
  '008347',
  '1'],
 ['Block Group 2, Census Tract 83.47, San Diego County, California',
  '65',
  '06',
  '073',
  '008347',
  '2'],
 ['Block Group 3, Census Tract 85.03, San Diego County, California',
  '60',
  '06',
  '073',
  '008503',
  '3'],
 ['Block Group 4, Census Tract 85.03, San Diego County, California',
  '109',
  '06',
  '073',
  '008503',
  '4'],
 ['Block Group 2, Census Tract 85.03, San Diego County, California',
  '54',
  '06',
  '073',
  '008503',
  '2'],
 ['Block Group 1, Census Tract 85.03, San Diego County, California',
  '67',
  '06',
  '073',
  '008503',
  '1'],
 ['Block Group 3, Census Tract 85.06, San Diego County, California',
  '10',
  '06',
  '073',
  '008506',
  '3'],
 ['Block Group 1, Census Tract 85.06, San Diego County, California',
  '48',
  '06',
  '073',
  '008506',
  '1'],
 ['Block Group 2, Census Tract 85.06, San Diego County, California',
  '29',
  '06',
  '073',
  '008506',
  '2'],
 ['Block Group 3, Census Tract 89.01, San Diego County, California',
  '0',
  '06',
  '073',
  '008901',
  '3'],
 ['Block Group 2, Census Tract 89.01, San Diego County, California',
  '60',
  '06',
  '073',
  '008901',
  '2'],
 ['Block Group 1, Census Tract 89.01, San Diego County, California',
  '98',
  '06',
  '073',
  '008901',
  '1'],
 ['Block Group 4, Census Tract 89.01, San Diego County, California',
  '0',
  '06',
  '073',
  '008901',
  '4'],
 ['Block Group 1, Census Tract 91.07, San Diego County, California',
  '116',
  '06',
  '073',
  '009107',
  '1'],
 ['Block Group 2, Census Tract 91.07, San Diego County, California',
  '0',
  '06',
  '073',
  '009107',
  '2'],
 ['Block Group 1, Census Tract 101.09, San Diego County, California',
  '0',
  '06',
  '073',
  '010109',
  '1'],
 ['Block Group 2, Census Tract 111, San Diego County, California',
  '28',
  '06',
  '073',
  '011100',
  '2'],
 ['Block Group 3, Census Tract 111, San Diego County, California',
  '25',
  '06',
  '073',
  '011100',
  '3'],
 ['Block Group 1, Census Tract 111, San Diego County, California',
  '62',
  '06',
  '073',
  '011100',
  '1'],
 ['Block Group 1, Census Tract 121.01, San Diego County, California',
  '78',
  '06',
  '073',
  '012101',
  '1'],
 ['Block Group 2, Census Tract 200.25, San Diego County, California',
  '53',
  '06',
  '073',
  '020025',
  '2'],
 ['Block Group 3, Census Tract 200.25, San Diego County, California',
  '48',
  '06',
  '073',
  '020025',
  '3'],
 ['Block Group 1, Census Tract 192.08, San Diego County, California',
  '0',
  '06',
  '073',
  '019208',
  '1'],
 ['Block Group 2, Census Tract 192.08, San Diego County, California',
  '8',
  '06',
  '073',
  '019208',
  '2'],
 ['Block Group 1, Census Tract 194.04, San Diego County, California',
  '46',
  '06',
  '073',
  '019404',
  '1'],
 ['Block Group 2, Census Tract 194.04, San Diego County, California',
  '71',
  '06',
  '073',
  '019404',
  '2'],
 ['Block Group 2, Census Tract 20.02, San Diego County, California',
  '66',
  '06',
  '073',
  '002002',
  '2'],
 ['Block Group 1, Census Tract 20.02, San Diego County, California',
  '40',
  '06',
  '073',
  '002002',
  '1'],
 ['Block Group 2, Census Tract 57, San Diego County, California',
  '0',
  '06',
  '073',
  '005700',
  '2'],
 ['Block Group 1, Census Tract 58, San Diego County, California',
  '0',
  '06',
  '073',
  '005800',
  '1'],
 ['Block Group 2, Census Tract 178.10, San Diego County, California',
  '41',
  '06',
  '073',
  '017810',
  '2'],
 ['Block Group 1, Census Tract 178.10, San Diego County, California',
  '27',
  '06',
  '073',
  '017810',
  '1'],
 ['Block Group 2, Census Tract 180, San Diego County, California',
  '35',
  '06',
  '073',
  '018000',
  '2'],
 ['Block Group 1, Census Tract 180, San Diego County, California',
  '0',
  '06',
  '073',
  '018000',
  '1'],
 ['Block Group 3, Census Tract 180, San Diego County, California',
  '15',
  '06',
  '073',
  '018000',
  '3'],

In [15]:
df4 = pd.DataFrame.from_dict(data)
df4

,0,1,2,3,4,5
0,NAME,B01001_004E,state,county,tract,block group
1,"Block Group 2, Census Tract 178.08, San Diego ...",82,06,073,017808,2
2,"Block Group 4, Census Tract 178.08, San Diego ...",33,06,073,017808,4
3,"Block Group 3, Census Tract 178.08, San Diego ...",49,06,073,017808,3
4,"Block Group 1, Census Tract 178.08, San Diego ...",0,06,073,017808,1
...,...,...,...,...,...,...
1791,"Block Group 1, Census Tract 171.09, San Diego ...",75,06,073,017109,1
1792,"Block Group 2, Census Tract 171.09, San Diego ...",28,06,073,017109,2
1793,"Block Group 3, Census Tract 171.09, San Diego ...",0,06,073,017109,3
1794,"Block Group 4, Census Tract 171.09, San Diego ...",39,06,073,017109,4
1795,"Block Group 1, Census Tract 171.10, San Diego ...",47,06,073,017110,1

In [16]:
df4.columns = df4.iloc[0]

#set first row as the column names in the dataframe

df4

,NAME,B01001_004E,state,county,tract,block group
0,NAME,B01001_004E,state,county,tract,block group
1,"Block Group 2, Census Tract 178.08, San Diego ...",82,06,073,017808,2
2,"Block Group 4, Census Tract 178.08, San Diego ...",33,06,073,017808,4
3,"Block Group 3, Census Tract 178.08, San Diego ...",49,06,073,017808,3
4,"Block Group 1, Census Tract 178.08, San Diego ...",0,06,073,017808,1
...,...,...,...,...,...,...
1791,"Block Group 1, Census Tract 171.09, San Diego ...",75,06,073,017109,1
1792,"Block Group 2, Census Tract 171.09, San Diego ...",28,06,073,017109,2
1793,"Block Group 3, Census Tract 171.09, San Diego ...",0,06,073,017109,3
1794,"Block Group 4, Census Tract 171.09, San Diego ...",39,06,073,017109,4
1795,"Block Group 1, Census Tract 171.10, San Diego ...",47,06,073,017110,1

In [17]:
df4 = df4.iloc[1:]
df4

#delete row 0 after renaming columns

,NAME,B01001_004E,state,county,tract,block group
1,"Block Group 2, Census Tract 178.08, San Diego ...",82,06,073,017808,2
2,"Block Group 4, Census Tract 178.08, San Diego ...",33,06,073,017808,4
3,"Block Group 3, Census Tract 178.08, San Diego ...",49,06,073,017808,3
4,"Block Group 1, Census Tract 178.08, San Diego ...",0,06,073,017808,1
5,"Block Group 1, Census Tract 191.01, San Diego ...",95,06,073,019101,1
...,...,...,...,...,...,...
1791,"Block Group 1, Census Tract 171.09, San Diego ...",75,06,073,017109,1
1792,"Block Group 2, Census Tract 171.09, San Diego ...",28,06,073,017109,2
1793,"Block Group 3, Census Tract 171.09, San Diego ...",0,06,073,017109,3
1794,"Block Group 4, Census Tract 171.09, San Diego ...",39,06,073,017109,4
1795,"Block Group 1, Census Tract 171.10, San Diego ...",47,06,073,017110,1

In [18]:
df4.NAME

1       Block Group 2, Census Tract 178.08, San Diego ...
2       Block Group 4, Census Tract 178.08, San Diego ...
3       Block Group 3, Census Tract 178.08, San Diego ...
4       Block Group 1, Census Tract 178.08, San Diego ...
5       Block Group 1, Census Tract 191.01, San Diego ...
                              ...
1791    Block Group 1, Census Tract 171.09, San Diego ...
1792    Block Group 2, Census Tract 171.09, San Diego ...
1793    Block Group 3, Census Tract 171.09, San Diego ...
1794    Block Group 4, Census Tract 171.09, San Diego ...
1795    Block Group 1, Census Tract 171.10, San Diego ...
Name: NAME, Length: 1795, dtype: object

In [ ]:
# del df['NAME']

# code if we decide to drop NAME column

## Dataframe for Total Male Estimates 10 - 14 years

B01001_005E = Estimate!!Total!!Male!!10 to 14 years

In [20]:
url5 = "https://api.census.gov/data/2017/acs/acs5?get=NAME,B01001_005E&for=block%20group:*&in=state:06%20county:073"

# B01001_005E added to url 

response = urlopen(url5)
data = loads(response.read())

data

;
# ; hide dict

''

In [21]:
df5 = pd.DataFrame.from_dict(data)

df5.columns = df5.iloc[0]

#set first row as the column names in the dataframe

df5

,NAME,B01001_005E,state,county,tract,block group
0,NAME,B01001_005E,state,county,tract,block group
1,"Block Group 2, Census Tract 178.08, San Diego ...",167,06,073,017808,2
2,"Block Group 4, Census Tract 178.08, San Diego ...",21,06,073,017808,4
3,"Block Group 3, Census Tract 178.08, San Diego ...",0,06,073,017808,3
4,"Block Group 1, Census Tract 178.08, San Diego ...",12,06,073,017808,1
...,...,...,...,...,...,...
1791,"Block Group 1, Census Tract 171.09, San Diego ...",170,06,073,017109,1
1792,"Block Group 2, Census Tract 171.09, San Diego ...",27,06,073,017109,2
1793,"Block Group 3, Census Tract 171.09, San Diego ...",0,06,073,017109,3
1794,"Block Group 4, Census Tract 171.09, San Diego ...",120,06,073,017109,4
1795,"Block Group 1, Census Tract 171.10, San Diego ...",14,06,073,017110,1

In [22]:
df5 = df5.iloc[1:]
df5

#delete row 0 after renaming columns

,NAME,B01001_005E,state,county,tract,block group
1,"Block Group 2, Census Tract 178.08, San Diego ...",167,06,073,017808,2
2,"Block Group 4, Census Tract 178.08, San Diego ...",21,06,073,017808,4
3,"Block Group 3, Census Tract 178.08, San Diego ...",0,06,073,017808,3
4,"Block Group 1, Census Tract 178.08, San Diego ...",12,06,073,017808,1
5,"Block Group 1, Census Tract 191.01, San Diego ...",120,06,073,019101,1
...,...,...,...,...,...,...
1791,"Block Group 1, Census Tract 171.09, San Diego ...",170,06,073,017109,1
1792,"Block Group 2, Census Tract 171.09, San Diego ...",27,06,073,017109,2
1793,"Block Group 3, Census Tract 171.09, San Diego ...",0,06,073,017109,3
1794,"Block Group 4, Census Tract 171.09, San Diego ...",120,06,073,017109,4
1795,"Block Group 1, Census Tract 171.10, San Diego ...",14,06,073,017110,1

In [23]:
df5.NAME

1       Block Group 2, Census Tract 178.08, San Diego ...
2       Block Group 4, Census Tract 178.08, San Diego ...
3       Block Group 3, Census Tract 178.08, San Diego ...
4       Block Group 1, Census Tract 178.08, San Diego ...
5       Block Group 1, Census Tract 191.01, San Diego ...
                              ...
1791    Block Group 1, Census Tract 171.09, San Diego ...
1792    Block Group 2, Census Tract 171.09, San Diego ...
1793    Block Group 3, Census Tract 171.09, San Diego ...
1794    Block Group 4, Census Tract 171.09, San Diego ...
1795    Block Group 1, Census Tract 171.10, San Diego ...
Name: NAME, Length: 1795, dtype: object

In [ ]:
# del df['NAME']

# code if we decide to drop NAME column

## Dataframe for Total Female Estimates 5 - 9 years

B01001_028E = Estimate!!Total!!Female!!5 to 9 years

In [29]:
url28 = "https://api.census.gov/data/2017/acs/acs5?get=NAME,B01001_028E&for=block%20group:*&in=state:06%20county:073"

# B01001_028E added to url

response = urlopen(url28)
data = loads(response.read())

data
;

''

In [30]:
df28 = pd.DataFrame.from_dict(data)

df28.columns = df28.iloc[0]

#set first row as the column names in the dataframe

df28

,NAME,B01001_028E,state,county,tract,block group
0,NAME,B01001_028E,state,county,tract,block group
1,"Block Group 2, Census Tract 178.08, San Diego ...",135,06,073,017808,2
2,"Block Group 4, Census Tract 178.08, San Diego ...",14,06,073,017808,4
3,"Block Group 3, Census Tract 178.08, San Diego ...",38,06,073,017808,3
4,"Block Group 1, Census Tract 178.08, San Diego ...",12,06,073,017808,1
...,...,...,...,...,...,...
1791,"Block Group 1, Census Tract 171.09, San Diego ...",240,06,073,017109,1
1792,"Block Group 2, Census Tract 171.09, San Diego ...",29,06,073,017109,2
1793,"Block Group 3, Census Tract 171.09, San Diego ...",23,06,073,017109,3
1794,"Block Group 4, Census Tract 171.09, San Diego ...",53,06,073,017109,4
1795,"Block Group 1, Census Tract 171.10, San Diego ...",0,06,073,017110,1

In [31]:
df28 = df28.iloc[1:]
df28

#delete row 0 after renaming columns

,NAME,B01001_028E,state,county,tract,block group
1,"Block Group 2, Census Tract 178.08, San Diego ...",135,06,073,017808,2
2,"Block Group 4, Census Tract 178.08, San Diego ...",14,06,073,017808,4
3,"Block Group 3, Census Tract 178.08, San Diego ...",38,06,073,017808,3
4,"Block Group 1, Census Tract 178.08, San Diego ...",12,06,073,017808,1
5,"Block Group 1, Census Tract 191.01, San Diego ...",43,06,073,019101,1
...,...,...,...,...,...,...
1791,"Block Group 1, Census Tract 171.09, San Diego ...",240,06,073,017109,1
1792,"Block Group 2, Census Tract 171.09, San Diego ...",29,06,073,017109,2
1793,"Block Group 3, Census Tract 171.09, San Diego ...",23,06,073,017109,3
1794,"Block Group 4, Census Tract 171.09, San Diego ...",53,06,073,017109,4
1795,"Block Group 1, Census Tract 171.10, San Diego ...",0,06,073,017110,1

In [32]:
df28.NAME

1       Block Group 2, Census Tract 178.08, San Diego ...
2       Block Group 4, Census Tract 178.08, San Diego ...
3       Block Group 3, Census Tract 178.08, San Diego ...
4       Block Group 1, Census Tract 178.08, San Diego ...
5       Block Group 1, Census Tract 191.01, San Diego ...
                              ...
1791    Block Group 1, Census Tract 171.09, San Diego ...
1792    Block Group 2, Census Tract 171.09, San Diego ...
1793    Block Group 3, Census Tract 171.09, San Diego ...
1794    Block Group 4, Census Tract 171.09, San Diego ...
1795    Block Group 1, Census Tract 171.10, San Diego ...
Name: NAME, Length: 1795, dtype: object

In [ ]:
# del df['NAME']

# code if we decide to drop NAME column

## Dataframe for Total Female Estimates 10 - 14 years

B01001_029E = Estimate!!Total!!Female!!10 to 14 years

In [37]:
url29 = "https://api.census.gov/data/2017/acs/acs5?get=NAME,B01001_029E&for=block%20group:*&in=state:06%20county:073"

#B01001_029E added to url

response = urlopen(url29)
data = loads(response.read())

data
;

''

In [38]:
df29 = pd.DataFrame.from_dict(data)

df29.columns = df29.iloc[0]

#set first row as the column names in the dataframe

df29

,NAME,B01001_029E,state,county,tract,block group
0,NAME,B01001_029E,state,county,tract,block group
1,"Block Group 2, Census Tract 178.08, San Diego ...",130,06,073,017808,2
2,"Block Group 4, Census Tract 178.08, San Diego ...",56,06,073,017808,4
3,"Block Group 3, Census Tract 178.08, San Diego ...",94,06,073,017808,3
4,"Block Group 1, Census Tract 178.08, San Diego ...",49,06,073,017808,1
...,...,...,...,...,...,...
1791,"Block Group 1, Census Tract 171.09, San Diego ...",176,06,073,017109,1
1792,"Block Group 2, Census Tract 171.09, San Diego ...",94,06,073,017109,2
1793,"Block Group 3, Census Tract 171.09, San Diego ...",43,06,073,017109,3
1794,"Block Group 4, Census Tract 171.09, San Diego ...",87,06,073,017109,4
1795,"Block Group 1, Census Tract 171.10, San Diego ...",86,06,073,017110,1

In [39]:
df29 = df29.iloc[1:]
df29

#delete row 0 after renaming columns

,NAME,B01001_029E,state,county,tract,block group
1,"Block Group 2, Census Tract 178.08, San Diego ...",130,06,073,017808,2
2,"Block Group 4, Census Tract 178.08, San Diego ...",56,06,073,017808,4
3,"Block Group 3, Census Tract 178.08, San Diego ...",94,06,073,017808,3
4,"Block Group 1, Census Tract 178.08, San Diego ...",49,06,073,017808,1
5,"Block Group 1, Census Tract 191.01, San Diego ...",21,06,073,019101,1
...,...,...,...,...,...,...
1791,"Block Group 1, Census Tract 171.09, San Diego ...",176,06,073,017109,1
1792,"Block Group 2, Census Tract 171.09, San Diego ...",94,06,073,017109,2
1793,"Block Group 3, Census Tract 171.09, San Diego ...",43,06,073,017109,3
1794,"Block Group 4, Census Tract 171.09, San Diego ...",87,06,073,017109,4
1795,"Block Group 1, Census Tract 171.10, San Diego ...",86,06,073,017110,1

In [36]:
df29.NAME

1       Block Group 2, Census Tract 178.08, San Diego ...
2       Block Group 4, Census Tract 178.08, San Diego ...
3       Block Group 3, Census Tract 178.08, San Diego ...
4       Block Group 1, Census Tract 178.08, San Diego ...
5       Block Group 1, Census Tract 191.01, San Diego ...
                              ...
1791    Block Group 1, Census Tract 171.09, San Diego ...
1792    Block Group 2, Census Tract 171.09, San Diego ...
1793    Block Group 3, Census Tract 171.09, San Diego ...
1794    Block Group 4, Census Tract 171.09, San Diego ...
1795    Block Group 1, Census Tract 171.10, San Diego ...
Name: NAME, Length: 1795, dtype: object

In [ ]:
# del df['NAME']

# code if we decide to drop NAME column

# Geographic Unit Variables from Urban

In [40]:
from urllib.request import urlopen
from json import loads
url = "https://educationdata.urban.org/api/v1/schools/nhgis/census-2010/2016/?state_mailing=CA&fips=06&county_fips_geo=06073"
response = urlopen(url)
data = loads(response.read())

# county_fips_geo = 06073 (San Diego)
# years available: 1986 - 2016 
# year = 2016

HTTPError: HTTP Error 500: Internal Server Error

In [ ]:
urban = pd.json_normalize(data, 'results')

urban

# Catchment (attendance boundaries) 

come courtesy of the [School Attendance Boundary Survey (SABS)](https://nces.ed.gov/programs/edge/SABS)

In [ ]:
#pip install geopandas

In [ ]:
import geopandas as gpd

In [ ]:
attbound = gpd.read_file("data/nces_att_bound/SABS_1516/SABS_1516.shp")