# NHGIS Database 

[NHGIS Data Selection](https://data2.nhgis.org/downloads/)

## Block unit

To access block level data apply the filter 
    Geographic Levels = BLOCK
    Topics            = Age and Race 
    
Datasets pulled from this filter results are: 8 total

    P12A. Sex by Age (White Alone) 
    P12B. Sex by Age (Black or African American Alone)
    P12C. Sex by Age (American Indian and Alaska Native Alone)  
    P12D. Sex by Age (Asian Alone)
    P12E. Sex by Age (Native Hawaiian and Other Pacific Islander Alone)
    P12F. Sex by Age (Some Other Race Alone)
    P12G. Sex by Age (Two or More Races)
    P12I. Sex by Age (White Alone, Not Hispanic or Latino)

## Block unit 

To navigate repo for data

In [3]:
import pandas as pd

In [4]:
blck = pd.read_csv("nhgis0023_ds172_2010_block.csv")

blck

#California only

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (18,19) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,GISJOIN,YEAR,REGIONA,DIVISIONA,STATE,STATEA,COUNTY,COUNTYA,COUSUBA,PLACEA,...,H9I040,H9I041,H9I042,H9I043,H9I044,H9I045,H9I046,H9I047,H9I048,H9I049
0,G06000104001001000,2010,4,9,California,6,Alameda County,1,92230,53000,...,0,0,0,0,0,0,0,0,0,0
1,G06000104001001001,2010,4,9,California,6,Alameda County,1,92230,53000,...,0,0,0,0,0,0,0,0,0,0
2,G06000104001001002,2010,4,9,California,6,Alameda County,1,92230,53000,...,0,0,0,0,0,0,0,0,0,0
3,G06000104001001003,2010,4,9,California,6,Alameda County,1,92230,53000,...,0,0,0,0,0,0,0,0,0,0
4,G06000104001001004,2010,4,9,California,6,Alameda County,1,92230,53000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
710140,G06011500411004062,2010,4,9,California,6,Yuba County,115,93830,12612,...,0,2,1,0,1,0,0,0,0,0
710141,G06011500411004063,2010,4,9,California,6,Yuba County,115,93830,12612,...,0,0,0,0,0,0,0,0,0,0
710142,G06011500411004064,2010,4,9,California,6,Yuba County,115,93830,12612,...,0,1,0,0,0,0,0,0,0,0
710143,G06011500411004065,2010,4,9,California,6,Yuba County,115,93830,12612,...,0,0,0,0,0,0,0,0,0,0
710144,G06011500411004066,2010,4,9,California,6,Yuba County,115,93830,12612,...,0,1,0,0,0,0,0,0,0,0

In [18]:
sdblck = blck[blck["COUNTY"] == 'San Diego County']
sdblck

#filtered San Diego block

,GISJOIN,YEAR,REGIONA,DIVISIONA,STATE,STATEA,COUNTY,COUNTYA,COUSUBA,PLACEA,...,H9I040,H9I041,H9I042,H9I043,H9I044,H9I045,H9I046,H9I047,H9I048,H9I049
484486,G06007300001001000,2010,4,9,California,6,San Diego County,73,92780,66000,...,8,8,2,6,5,8,6,4,4,3
484487,G06007300001001001,2010,4,9,California,6,San Diego County,73,92780,66000,...,0,0,0,0,0,0,1,0,0,0
484488,G06007300001001002,2010,4,9,California,6,San Diego County,73,92780,66000,...,1,1,0,0,0,0,0,0,1,0
484489,G06007300001001003,2010,4,9,California,6,San Diego County,73,92780,66000,...,3,3,0,1,1,1,0,0,1,0
484490,G06007300001001004,2010,4,9,California,6,San Diego County,73,92780,66000,...,1,1,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527896,G06007309901000041,2010,4,9,California,6,San Diego County,73,92780,66000,...,0,0,0,0,0,0,0,0,0,0
527897,G06007309901000042,2010,4,9,California,6,San Diego County,73,92780,99999,...,0,0,0,0,0,0,0,0,0,0
527898,G06007309901000043,2010,4,9,California,6,San Diego County,73,92780,99999,...,0,0,0,0,0,0,0,0,0,0
527899,G06007309901000044,2010,4,9,California,6,San Diego County,73,92780,99999,...,0,0,0,0,0,0,0,0,0,0
527900,G06007309901000045,2010,4,9,California,6,San Diego County,73,92780,99999,...,0,0,0,0,0,0,0,0,0,0

In [1]:
blck.BLOCKA
#checking block

NameError: name 'blck' is not defined

In [13]:
blck.BLKGRPA
#checking block group

0         1
1         1
2         1
3         1
4         1
         ..
710140    4
710141    4
710142    4
710143    4
710144    4
Name: BLKGRPA, Length: 710145, dtype: int64

In [14]:
blck.TRACTA
#checking tract

0         400100
1         400100
2         400100
3         400100
4         400100
           ...
710140     41100
710141     41100
710142     41100
710143     41100
710144     41100
Name: TRACTA, Length: 710145, dtype: int64

## Block Group unit

To access block group level data apply the filter 
    Geographic Levels = BLCK_GRP
    Topics            = Age and Race 
    
Datasets pulled from this filter results are: 8 total

    P12A. Sex by Age (White Alone) 
    P12B. Sex by Age (Black or African American Alone)
    P12C. Sex by Age (American Indian and Alaska Native Alone)  
    P12D. Sex by Age (Asian Alone)
    P12E. Sex by Age (Native Hawaiian and Other Pacific Islander Alone)
    P12F. Sex by Age (Some Other Race Alone)
    P12G. Sex by Age (Two or More Races)
    P12I. Sex by Age (White Alone, Not Hispanic or Latino)

In [14]:
blckgrp = pd.read_csv("nhgis0022_ds172_2010_blck_grp.csv")
blckgrp

,GISJOIN,YEAR,REGIONA,DIVISIONA,STATE,STATEA,COUNTY,COUNTYA,COUSUBA,PLACEA,...,H9I040,H9I041,H9I042,H9I043,H9I044,H9I045,H9I046,H9I047,H9I048,H9I049
0,G06000104001001,2010,4,9,California,6,Alameda County,1,NaN,NaN,...,98,121,64,85,35,59,55,43,40,27
1,G06000104002001,2010,4,9,California,6,Alameda County,1,NaN,NaN,...,34,30,18,30,25,18,20,12,9,7
2,G06000104002002,2010,4,9,California,6,Alameda County,1,NaN,NaN,...,15,13,11,17,13,15,15,3,4,5
3,G06000104003001,2010,4,9,California,6,Alameda County,1,NaN,NaN,...,32,28,23,23,13,13,8,8,1,6
4,G06000104003002,2010,4,9,California,6,Alameda County,1,NaN,NaN,...,36,22,10,11,2,7,6,4,9,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23207,G06011500410005,2010,4,9,California,6,Yuba County,115,NaN,NaN,...,31,21,8,20,13,13,13,7,6,9
23208,G06011500411001,2010,4,9,California,6,Yuba County,115,NaN,NaN,...,45,42,17,34,18,16,24,14,3,7
23209,G06011500411002,2010,4,9,California,6,Yuba County,115,NaN,NaN,...,64,79,39,38,27,25,24,20,23,11
23210,G06011500411003,2010,4,9,California,6,Yuba County,115,NaN,NaN,...,53,50,15,26,28,15,27,24,17,11
23211,G06011500411004,2010,4,9,California,6,Yuba County,115,NaN,NaN,...,37,40,18,35,10,15,25,20,16,10

In [16]:
sdblckgrp = blckgrp[blckgrp["COUNTY"] == 'San Diego County']

sdblckgrp

#filtered San Diego Block Group level

,GISJOIN,YEAR,REGIONA,DIVISIONA,STATE,STATEA,COUNTY,COUNTYA,COUSUBA,PLACEA,...,H9I040,H9I041,H9I042,H9I043,H9I044,H9I045,H9I046,H9I047,H9I048,H9I049
16041,G06007300001001,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,56,59,23,32,22,35,24,17,14,17
16042,G06007300001002,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,66,62,32,64,26,21,39,33,33,35
16043,G06007300002011,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,50,55,29,50,21,28,46,37,22,54
16044,G06007300002021,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,33,46,19,19,2,11,18,9,11,17
16045,G06007300002022,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,21,16,10,5,4,9,9,10,4,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17831,G06007300220002,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,6,4,1,2,5,2,2,7,2,4
17832,G06007300221001,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,82,70,20,25,24,10,23,22,26,20
17833,G06007300221002,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,87,67,23,32,19,20,30,24,14,6
17834,G06007300221003,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,100,76,35,35,22,32,37,24,16,12
17835,G06007309901000,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

In [11]:
blckgrp.BLOCKA

#blocks unavailable

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
23207   NaN
23208   NaN
23209   NaN
23210   NaN
23211   NaN
Name: BLOCKA, Length: 23212, dtype: float64

In [10]:
blckgrp.BLKGRPA
# block group

0        1
1        1
2        2
3        1
4        2
        ..
23207    5
23208    1
23209    2
23210    3
23211    4
Name: BLKGRPA, Length: 23212, dtype: int64

In [7]:
blckgrp.TRACTA
#tracts

0        400100
1        400200
2        400200
3        400300
4        400300
          ...
23207     41000
23208     41100
23209     41100
23210     41100
23211     41100
Name: TRACTA, Length: 23212, dtype: int64

## Tract unit

To access block group level data apply the filter 
    Geographic Levels = TRACT
    Topics            = Age and Race 
    
Datasets pulled from this filter results are: 8 total

    P12A. Sex by Age (White Alone) 
    P12B. Sex by Age (Black or African American Alone)
    P12C. Sex by Age (American Indian and Alaska Native Alone)  
    P12D. Sex by Age (Asian Alone)
    P12E. Sex by Age (Native Hawaiian and Other Pacific Islander Alone)
    P12F. Sex by Age (Some Other Race Alone)
    P12G. Sex by Age (Two or More Races)
    P12I. Sex by Age (White Alone, Not Hispanic or Latino)

In [19]:
trct = pd.read_csv("nhgis0020_ds172_2010_tract.csv",encoding = 'ISO-8859-1')
trct

,GISJOIN,YEAR,REGIONA,DIVISIONA,STATE,STATEA,COUNTY,COUNTYA,COUSUBA,PLACEA,...,H9I040,H9I041,H9I042,H9I043,H9I044,H9I045,H9I046,H9I047,H9I048,H9I049
0,G0100010020100,2010,3,6,Alabama,1,Autauga County,1,NaN,NaN,...,65,53,24,32,16,21,34,22,12,8
1,G0100010020200,2010,3,6,Alabama,1,Autauga County,1,NaN,NaN,...,27,17,6,12,5,16,12,10,7,7
2,G0100010020300,2010,3,6,Alabama,1,Autauga County,1,NaN,NaN,...,91,85,30,47,23,47,57,44,26,19
3,G0100010020400,2010,3,6,Alabama,1,Autauga County,1,NaN,NaN,...,132,128,45,78,54,72,149,110,64,51
4,G0100010020500,2010,3,6,Alabama,1,Autauga County,1,NaN,NaN,...,292,200,92,117,60,112,168,102,88,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73997,G7201530750501,2010,9,0,Puerto Rico,72,Yauco Municipio,153,NaN,NaN,...,2,0,0,0,0,4,0,0,0,0
73998,G7201530750502,2010,9,0,Puerto Rico,72,Yauco Municipio,153,NaN,NaN,...,1,0,0,0,0,0,0,1,0,0
73999,G7201530750503,2010,9,0,Puerto Rico,72,Yauco Municipio,153,NaN,NaN,...,4,0,0,0,1,0,0,0,0,0
74000,G7201530750601,2010,9,0,Puerto Rico,72,Yauco Municipio,153,NaN,NaN,...,1,0,0,0,0,0,0,0,0,1
74001,G7201530750602,2010,9,0,Puerto Rico,72,Yauco Municipio,153,NaN,NaN,...,1,1,0,0,0,0,0,0,0,0

In [21]:
sdtrct = ca[ca['COUNTY'] == 'San Diego County']
sdtrct

,GISJOIN,YEAR,REGIONA,DIVISIONA,STATE,STATEA,COUNTY,COUNTYA,COUSUBA,PLACEA,...,H9I040,H9I041,H9I042,H9I043,H9I044,H9I045,H9I046,H9I047,H9I048,H9I049
9218,G0600730000100,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,122,121,55,96,48,56,63,50,47,52
9219,G0600730000201,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,50,55,29,50,21,28,46,37,22,54
9220,G0600730000202,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,105,124,53,63,21,37,55,48,40,73
9221,G0600730000300,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,85,85,44,80,37,25,59,63,67,89
9222,G0600730000400,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,57,57,23,38,20,24,28,30,20,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9841,G0600730021800,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,86,74,30,36,25,27,41,54,38,63
9842,G0600730021900,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,3,7,2,3,1,1,1,3,0,0
9843,G0600730022000,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,14,9,4,3,6,2,5,12,9,24
9844,G0600730022100,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,269,213,78,92,65,62,90,70,56,38
9845,G0600730990100,2010,4,9,California,6,San Diego County,73,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

In [23]:
sd.BLOCKA
#no block level

9218   NaN
9219   NaN
9220   NaN
9221   NaN
9222   NaN
        ..
9841   NaN
9842   NaN
9843   NaN
9844   NaN
9845   NaN
Name: BLOCKA, Length: 628, dtype: float64

In [26]:
sd.BLKGRPA

#no block group

9218   NaN
9219   NaN
9220   NaN
9221   NaN
9222   NaN
        ..
9841   NaN
9842   NaN
9843   NaN
9844   NaN
9845   NaN
Name: BLKGRPA, Length: 628, dtype: float64

In [27]:
sd.TRACTA

9218       100
9219       201
9220       202
9221       300
9222       400
         ...
9841     21800
9842     21900
9843     22000
9844     22100
9845    990100
Name: TRACTA, Length: 628, dtype: int64